services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./application:/var/www/html
    networks:
      - yii2-network
    restart: unless-stopped
    env_file: "./.env"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./application:/var/www/html
    ports:
      - "${PORT_1}:80"
    depends_on:
      - php-fpm
    networks:
      - yii2-network
    restart: unless-stopped

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PORT_2}:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - yii2-network
    restart: unless-stopped
volumes:
  dbdata:

networks:
  yii2-network:
    driver: bridge
