services:
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./application:/var/www/html
    networks:
      - yii2-network
    restart: unless-stopped
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./application:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - yii2-network
    restart: unless-stopped

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2app
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yii2password
    ports:
      - "3336:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - yii2-network
    restart: unless-stopped
volumes:
  dbdata:

networks:
  yii2-network:
    driver: bridge
